### ISSUE TITLE
Add parenthesis to completions of methods and functions 

### ISSUE THREAD

**Issue by noib3** [pappasam/coc-jedi#20] opened 2021-01-20 20:22 UTC
Basically title. It'd be nice to complete `object.` with `object.method()` instead of `object.method`. Sometimes the parenthesis won't be needed, but pressing backspace once in a while is better than manually inputing parenthesis almost every time.

**Comment by pappasam** [comment] 2021-01-20 22:05
Thanks for the issue. Note: this is already implemented using snippets. If you have the following mapping in your vimrc:

```vim
imap     <silent> <expr> <C-l> coc#expandable() ? "<Plug>(coc-snippets-expand)" : "\<C-y>"
```

And you've installed [coc-snippets](https://github.com/neoclide/coc-snippets), pressing `<C-l>` while you've selected a callable should expand both the parentheses and the non-keyword arguments. See:

![snippet_example](https://user-images.githubusercontent.com/3723671/105246082-9a915500-5b27-11eb-8f5c-322b45c1d433.gif)

Given the fact that adding a parenthesis for all callables creates unexpected problems (see [here](https://github.com/microsoft/python-language-server/issues/573)), I've opted to keep this functionality within snippets instead of causing unexpected behavior for end users during imports, snippet expansion, etc.

**Comment by pappasam** [comment] 2021-01-20 22:17
Actually, I might have an idea for how to implement this without creating problems elsewhere. I'll keep this issue open until I've figured that out 1 way or another. The solution will involve both <https://jedi.readthedocs.io/en/latest/docs/settings.html#jedi.settings.add_bracket_after_function> and making sure that doesn't create weird behavior on imports and snippet expansion.

**Comment by pappasam** [comment] 2021-03-28 15:33
Ok second thought, since this is handled by snippets, and because I can't think of a good way to include this without creating weird edge cases, I'll close this issue.

**Closed by pappasam** 2021-03-28 15:33 UTC
