### ISSUE TITLE
I'm not getting autocomplete from pip modules

### ISSUE THREAD

**Issue by kevinpita** [pappasam/coc-jedi#11] opened 2020-08-27 02:23 UTC
I'm trying to make a flask app and I'm not getting any complete for app object

```
from flask import Flask

app = Flask(__name__)
```

I don't get anything from it, how could I do to get coc-jedi to support external modules?
it works flawless with python own packages

**Comment by pappasam** [comment] 2020-08-27 04:03
@kpg02 Can you please provide more information? Vim or Neovim, are you developing in a virtualenv or not in a virtualenv, what is your python version, are you using conda  or pypi, etc. The solution (or lack thereof) I have for you will depend on which combination of the above you are using.

**Comment by kpg02** [comment] 2020-08-27 08:12
I'm using nvim 0.5 installed with homebrew

I'm not using a virtualenv

python 3.8.3

pypi

Thanks for the fast response

**Comment by pappasam** [comment] 2020-08-27 17:08
You've found a bug! That said, there's a work-around for you to get the functionality you want.

If you don't want to use a virtualenv but you do want to access code installed in your system's site-packages, do the following:

1. Install `jedi-language-server` system-wide: `pip install jedi-language-server`
2. In your `coc-settings.json`, add the following line: `  "jedi.executable.command": "jedi-language-server",`

Note: if you choose this strategy, you'll be responsible for installing / updating jedi-language-server on your own.

**Comment by prmammoth** [comment] 2021-01-24 15:30
And what if one does use a virtualenv?

**Comment by pappasam** [comment] 2021-01-25 01:54
@prmammoth If you do use a virtualenv, you should get autocompletion from pip-installed modules out of the box. Please let me know if that's not the case.

**Comment by Houkime** [comment] 2021-07-24 08:57
The workaround works, but it really feels like this should be fixed.
Jedi itself is capable of determining whether it is used for a virtualenv or not, so the jedi-coc should be at least as versatile.

**Comment by pappasam** [comment] 2021-07-24 18:08
@Houkime yes, i agree; that's why I've kept this issue open. Happy to review any pr's and / or consider productive suggestions! This particular issue may be an edge case within Jedi itself. Or, possibly, there's something simple we can do here. Either way, the issue is still open because it's unsolved and important.

**Comment by pappasam** [comment] 2021-12-03 19:44
Should be generally resolved by: https://github.com/pappasam/coc-jedi/commit/18458a9c13f00e63ab9d884e876b89330d3dfaea

**Closed by pappasam** 2021-12-03 19:44 UTC
Labels: bug
